### PR TITLE
Create CHERRY_PCB_175STEP.kicad_mod

### PR DESCRIPTION
**Pull request by Dbroqua**
Added Cherry 1.75U stepped.

### CODE REVIEW

**Comment by BathroomEpiphanies** [comment]
Not a bad idea. I'm just very slow... I added a cleaned up version as well as an ISO enter shape.

Thanks!

**Comment by Dbroqua** [comment]
Hello,

I've closed my PR because I've made an error in the sizing (1U for the base and not 1.25U).

Damien

**Comment by BathroomEpiphanies** [comment]
I actually think the file in the link above is correct. (Is it possible that it has changed?) The distance of the stem from the left edge of the key corresponds to that of a 1.25u wide key.

**Comment by Dbroqua** [comment]
Yes it's possible :D

**Comment by BathroomEpiphanies** [comment]
I just assumed it would point to the version of the file being requested for the pull =) Anyway the one I added to the repository should be correct.

**Pull request closed without merging**
